### ISSUE TITLE
틀

### ISSUE THREAD

**Issue by ss35789** [kreimben/android_sns_app#1]
- [x] 로그인, 로그아웃.
- [x] 로그인 성공시 게시판에 데이터 불러옴, 친구데이터 불러옴.
- [x] 친구 follow 기능, 친구 unfollow 기능.
- [x] 게시물 올리기 기능, 삭제기능.
- [x] User(displayname, email, following, photourl, uid)
- [x] 게시물(content, created_at, image_uri, title, user)

-------------- Optional ---------------

- [x] 계정삭제 기능
- [x] 계정편집 기능 => **프로필 변경으로 대체**
- [x] ~~게시물에 댓글 추가 삭제기능, (좋아요 기능)~~ => **구현하지 않음**
- [x] ~~친구 계정 들어가면 해당 인물의 email, 게시글만 볼 수 있음~~ => **구현하지 않음**
- [x] ~~친구 상태열람 기능 (online)~~ => **구현하지 않음 (웹소켓 연결해야함)**
- [x] ~~오프라인 설정, 차단 기능(해당 상대의 게시글은 안보임)~~ => **구현하지 않음**
- [x] ~~게시글 편집 기능~~ => **구현 하지 않음**

**Comment by kreimben** [comment]
# 프로필 관련

내가 할일
* 프로필 이름 (`displayName`)
* 프로필 사진 업로드 (최종 다운로드 가능한 `Uri`객체)

구현이 목표.
