### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by kreimben** [kreimben/android_sns_app#11]
1. `MainActivity.kt`에서 100, 102 line `user`를 `uid`로 수정함.
2. 내가 올린 글이 아닌데 내 닉네임으로 표시됨. 고쳐야 함.
3. 사진 사이즈 맞춰서 레이아웃 다시 짜기

https://github.com/kreimben/android_sns_app/commit/afc4c93f22844752bedd8ced6a7f4eea6dd42408

@ss35789

**Comment by ss35789** [comment]
확인 이번주 안으로 수정
